import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
        {children}
        <footer className="footer footer-center p-4 bg-base-200 text-base-content fixed inset-x-0 bottom-0">
          <div>
            <p> Made by samsaq#2860 |{" "} <a className="underline underline-offset-2" href="https://github.com/samsaq">Github</a></p>
          </div>
        </footer>
      </body>
    </html>
  );
}
